//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenixAutomat
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunicationMessagesKittingsApprovalKitsSerNumSent
    {
        public int ID { get; set; }
        public int ApprovalKitsID { get; set; }
        public string SN1 { get; set; }
        public string SN2 { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int ModifyUserId { get; set; }
    }
}
