//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenixAutomat
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunicationMessagesReceptionConfirmationItems
    {
        public int ID { get; set; }
        public int CMSOId { get; set; }
        public int ItemID { get; set; }
        public string ItemDescription { get; set; }
        public decimal ItemQuantity { get; set; }
        public string ItemUnitOfMeasure { get; set; }
        public int ItemQualityId { get; set; }
        public string NDReceipt { get; set; }
        public string ItemSNs { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int ModifyUserId { get; set; }
        public int SNExportedFlag { get; set; }
        public Nullable<System.DateTime> SNExportedDate { get; set; }
    
        public virtual cdlItems cdlItems { get; set; }
    }
}
