//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenixAutomat
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunicationMessagesShipmentOrdersConfirmationItems
    {
        public int ID { get; set; }
        public int CMSOId { get; set; }
        public int SingleOrMaster { get; set; }
        public Nullable<int> HeliosOrderRecordID { get; set; }
        public int ItemVerKit { get; set; }
        public int ItemOrKitID { get; set; }
        public string ItemOrKitDescription { get; set; }
        public decimal ItemOrKitQuantity { get; set; }
        public int ItemOrKitUnitOfMeasureId { get; set; }
        public string ItemOrKitUnitOfMeasure { get; set; }
        public int ItemOrKitQualityId { get; set; }
        public string ItemOrKitQualityCode { get; set; }
        public Nullable<int> IncotermsId { get; set; }
        public string IncotermDescription { get; set; }
        public Nullable<System.DateTime> RealDateOfDelivery { get; set; }
        public Nullable<decimal> RealItemOrKitQuantity { get; set; }
        public Nullable<int> RealItemOrKitQualityID { get; set; }
        public string RealItemOrKitQuality { get; set; }
        public Nullable<int> Status { get; set; }
        public string KitSNs { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int ModifyUserId { get; set; }
    }
}
