//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenixAutomat
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunicationMessagesCrmOrder
    {
        public CommunicationMessagesCrmOrder()
        {
            this.CommunicationMessagesCrmOrderItems = new HashSet<CommunicationMessagesCrmOrderItems>();
        }
    
        public int ID { get; set; }
        public int MessageID { get; set; }
        public int MessageTypeID { get; set; }
        public string MessageDescription { get; set; }
        public Nullable<System.DateTime> MessageDateOfShipment { get; set; }
        public int MessageStatusID { get; set; }
        public string WO_PR_NUMBER { get; set; }
        public System.DateTime WO_PR_CREATE_DATE { get; set; }
        public System.DateTime WO_DELIVERY_DATE_FROM { get; set; }
        public System.DateTime WO_DELIVERY_DATE_TO { get; set; }
        public int WO_CID { get; set; }
        public string WO_FIRST_LAST_NAME { get; set; }
        public string WO_STREET_NAME { get; set; }
        public string WO_HOUSE_NUMBER { get; set; }
        public string WO_CITY { get; set; }
        public string WO_ZIP { get; set; }
        public string WO_PHONE { get; set; }
        public string WO_EMAIL_INFO1 { get; set; }
        public string WO_PR_TYPE { get; set; }
        public string WO_FLOOR_FLAT { get; set; }
        public string WO_UPC_TEL1 { get; set; }
        public string WO_UPC_TEL2 { get; set; }
        public string WO_EMAIL { get; set; }
        public string WO_PASSWORD { get; set; }
        public string WO_CPE_BACK { get; set; }
        public string WO_NOTE { get; set; }
        public string F_CUSTOMER_TYPE { get; set; }
        public int F_PR_TYPE { get; set; }
        public string F_RENTAL { get; set; }
        public string F_SALE { get; set; }
        public string F_INET_CORE_PRODUCT { get; set; }
        public int F_ZICYZ_ID { get; set; }
        public string L_TYPE_OF_ORDER { get; set; }
        public System.DateTime L_SHIPMENT_EXPECTED { get; set; }
        public Nullable<bool> X_DELIVERY { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int ModifyUserID { get; set; }
    
        public virtual ICollection<CommunicationMessagesCrmOrderItems> CommunicationMessagesCrmOrderItems { get; set; }
    }
}
