//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenixAutomat
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunicationMessagesKittingsConfirmation
    {
        public int ID { get; set; }
        public int MessageId { get; set; }
        public int MessageTypeId { get; set; }
        public string MessageDescription { get; set; }
        public Nullable<System.DateTime> MessageDateOfReceipt { get; set; }
        public int KitOrderID { get; set; }
        public int Reconciliation { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int ModifyUserId { get; set; }
    
        public virtual CommunicationMessagesReceptionSent CommunicationMessagesReceptionSent { get; set; }
    }
}
