//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenixAutomat
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunicationMessagesDeleteMessage
    {
        public int ID { get; set; }
        public int MessageId { get; set; }
        public int MessageTypeId { get; set; }
        public string MessageTypeDescription { get; set; }
        public int MessageStatusId { get; set; }
        public int DeleteId { get; set; }
        public int DeleteMessageId { get; set; }
        public int DeleteMessageTypeId { get; set; }
        public string DeleteMessageTypeDescription { get; set; }
        public string Notice { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<int> SentUserId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int ModifyUserId { get; set; }
    }
}
