//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenixAutomat
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunicationMessagesKittingsSent
    {
        public int ID { get; set; }
        public int MessageId { get; set; }
        public int MessageType { get; set; }
        public string MessageDescription { get; set; }
        public Nullable<System.DateTime> MessageDateOfShipment { get; set; }
        public int MessageStatusId { get; set; }
        public int HeliosOrderId { get; set; }
        public System.DateTime KitDateOfDelivery { get; set; }
        public Nullable<bool> IsManually { get; set; }
        public string Notice { get; set; }
        public int StockId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int ModifyUserId { get; set; }
    }
}
