//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenixAutomat
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunicationMessagesReceptionSentItems
    {
        public int ID { get; set; }
        public int CMSOId { get; set; }
        public Nullable<int> HeliosOrderId { get; set; }
        public Nullable<int> HeliosOrderRecordId { get; set; }
        public int ItemID { get; set; }
        public string GroupGoods { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public decimal ItemQuantity { get; set; }
        public Nullable<decimal> ItemQuantityDelivered { get; set; }
        public int MeasuresID { get; set; }
        public string ItemUnitOfMeasure { get; set; }
        public int ItemQualityId { get; set; }
        public string ItemQualityCode { get; set; }
        public Nullable<int> SourceId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int ModifyUserId { get; set; }
    }
}
