//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenixAutomat
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunicationMessagesCrmOrderItems
    {
        public int ID { get; set; }
        public int CommunicationMessageID { get; set; }
        public bool L_ITEM_VER_KIT { get; set; }
        public int L_ITEM_OR_KIT_ID { get; set; }
        public string L_ITEM_OR_KIT_DESCRIPTION { get; set; }
        public string L_ITEM_OR_KIT_QUALITY { get; set; }
        public int L_ITEM_OR_KIT_QUALITY_ID { get; set; }
        public decimal L_ITEM_OR_KIT_QUANTITY { get; set; }
        public int L_ITEM_OR_KIT_MEASURE_ID { get; set; }
        public string L_ITEM_OR_KIT_MEASURE { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int ModifyUserID { get; set; }
    
        public virtual CommunicationMessagesCrmOrder CommunicationMessagesCrmOrder { get; set; }
    }
}
