//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenixAutomat
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunicationMessagesKittingsApprovalKitsSent
    {
        public int ID { get; set; }
        public int ApprovalID { get; set; }
        public int KitID { get; set; }
        public string KitDescription { get; set; }
        public decimal KitQuantity { get; set; }
        public int KitUnitOfMeasureID { get; set; }
        public string KitUnitOfMeasure { get; set; }
        public int KitQualityId { get; set; }
        public string KitQuality { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int ModifyUserId { get; set; }
    }
}
