//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenixAutomat
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunicationMessagesKittingsSentItems
    {
        public int ID { get; set; }
        public int CMSOId { get; set; }
        public int HeliosOrderID { get; set; }
        public int HeliosOrderRecordId { get; set; }
        public int KitId { get; set; }
        public string KitDescription { get; set; }
        public decimal KitQuantity { get; set; }
        public Nullable<decimal> KitQuantityDelivered { get; set; }
        public int MeasuresID { get; set; }
        public string KitUnitOfMeasure { get; set; }
        public int KitQualityId { get; set; }
        public string KitQualityCode { get; set; }
        public int CardStockItemsId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int ModifyUserId { get; set; }
    }
}
