//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenixAutomat
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailReceived
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public string EmailSubject { get; set; }
        public string EmailParsedSubject { get; set; }
        public string EmailParsedSubjectHash { get; set; }
        public string EmailMessage { get; set; }
        public string Source { get; set; }
        public bool IsExternal { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int ModifyUserId { get; set; }
        public string EmailFrom { get; set; }
    }
}
