//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenixAutomat
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FenixEntities : DbContext
    {
        public FenixEntities()
            : base("name=FenixEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cdlItems> cdlItems { get; set; }
        public virtual DbSet<cdlKits> cdlKits { get; set; }
        public virtual DbSet<CommunicationMessagesKittingsApprovalKitsSent> CommunicationMessagesKittingsApprovalKitsSent { get; set; }
        public virtual DbSet<CommunicationMessagesKittingsApprovalKitsSerNumSent> CommunicationMessagesKittingsApprovalKitsSerNumSent { get; set; }
        public virtual DbSet<CommunicationMessagesKittingsApprovalSent> CommunicationMessagesKittingsApprovalSent { get; set; }
        public virtual DbSet<CommunicationMessagesKittingsConfirmation> CommunicationMessagesKittingsConfirmation { get; set; }
        public virtual DbSet<CommunicationMessagesKittingsConfirmationItems> CommunicationMessagesKittingsConfirmationItems { get; set; }
        public virtual DbSet<CommunicationMessagesKittingsSent> CommunicationMessagesKittingsSent { get; set; }
        public virtual DbSet<CommunicationMessagesKittingsSentItems> CommunicationMessagesKittingsSentItems { get; set; }
        public virtual DbSet<CommunicationMessagesReceptionConfirmation> CommunicationMessagesReceptionConfirmation { get; set; }
        public virtual DbSet<CommunicationMessagesReceptionConfirmationItems> CommunicationMessagesReceptionConfirmationItems { get; set; }
        public virtual DbSet<CommunicationMessagesReceptionSent> CommunicationMessagesReceptionSent { get; set; }
        public virtual DbSet<CommunicationMessagesShipmentOrdersConfirmation> CommunicationMessagesShipmentOrdersConfirmation { get; set; }
        public virtual DbSet<CommunicationMessagesShipmentOrdersConfirmationItems> CommunicationMessagesShipmentOrdersConfirmationItems { get; set; }
        public virtual DbSet<CommunicationMessagesShipmentOrdersSent> CommunicationMessagesShipmentOrdersSent { get; set; }
        public virtual DbSet<CommunicationMessagesShipmentOrdersSentItems> CommunicationMessagesShipmentOrdersSentItems { get; set; }
        public virtual DbSet<cdlKitsItems> cdlKitsItems { get; set; }
        public virtual DbSet<CommunicationMessagesReceptionSentItems> CommunicationMessagesReceptionSentItems { get; set; }
        public virtual DbSet<CommunicationMessagesRefurbishedOrder> CommunicationMessagesRefurbishedOrder { get; set; }
        public virtual DbSet<CommunicationMessagesRefurbishedOrderItems> CommunicationMessagesRefurbishedOrderItems { get; set; }
        public virtual DbSet<EmailSent> EmailSent { get; set; }
        public virtual DbSet<DeleteMessageSent> DeleteMessageSent { get; set; }
        public virtual DbSet<vwCMKSent> vwCMKSent { get; set; }
        public virtual DbSet<vwShipmentOrderIt> vwShipmentOrderIt { get; set; }
        public virtual DbSet<vwCMRF0SentIt> vwCMRF0SentIt { get; set; }
        public virtual DbSet<vwCMRF0Sent> vwCMRF0Sent { get; set; }
        public virtual DbSet<CardStockItems> CardStockItems { get; set; }
        public virtual DbSet<EmailReceived> EmailReceived { get; set; }
        public virtual DbSet<InternalDocuments> InternalDocuments { get; set; }
        public virtual DbSet<CommunicationMessagesDeleteMessage> CommunicationMessagesDeleteMessage { get; set; }
        public virtual DbSet<CommunicationMessagesCrmOrder> CommunicationMessagesCrmOrder { get; set; }
        public virtual DbSet<CommunicationMessagesCrmOrderItems> CommunicationMessagesCrmOrderItems { get; set; }
    
        public virtual int prKittingsApprovalSetSent(Nullable<int> receptionOrderID, Nullable<int> messageStatusID, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var receptionOrderIDParameter = receptionOrderID.HasValue ?
                new ObjectParameter("ReceptionOrderID", receptionOrderID) :
                new ObjectParameter("ReceptionOrderID", typeof(int));
    
            var messageStatusIDParameter = messageStatusID.HasValue ?
                new ObjectParameter("MessageStatusID", messageStatusID) :
                new ObjectParameter("MessageStatusID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prKittingsApprovalSetSent", receptionOrderIDParameter, messageStatusIDParameter, returnValue, returnMessage);
        }
    
        public virtual int prKittingsOrderSetSent(Nullable<int> receptionOrderID, Nullable<int> messageStatusID, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var receptionOrderIDParameter = receptionOrderID.HasValue ?
                new ObjectParameter("ReceptionOrderID", receptionOrderID) :
                new ObjectParameter("ReceptionOrderID", typeof(int));
    
            var messageStatusIDParameter = messageStatusID.HasValue ?
                new ObjectParameter("MessageStatusID", messageStatusID) :
                new ObjectParameter("MessageStatusID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prKittingsOrderSetSent", receptionOrderIDParameter, messageStatusIDParameter, returnValue, returnMessage);
        }
    
        public virtual int prReceptionOrderSetSent(Nullable<int> receptionOrderID, Nullable<int> messageStatusID, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var receptionOrderIDParameter = receptionOrderID.HasValue ?
                new ObjectParameter("ReceptionOrderID", receptionOrderID) :
                new ObjectParameter("ReceptionOrderID", typeof(int));
    
            var messageStatusIDParameter = messageStatusID.HasValue ?
                new ObjectParameter("MessageStatusID", messageStatusID) :
                new ObjectParameter("MessageStatusID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prReceptionOrderSetSent", receptionOrderIDParameter, messageStatusIDParameter, returnValue, returnMessage);
        }
    
        public virtual int prShipmentOrderSetSent(Nullable<int> receptionOrderID, Nullable<int> messageStatusID, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var receptionOrderIDParameter = receptionOrderID.HasValue ?
                new ObjectParameter("ReceptionOrderID", receptionOrderID) :
                new ObjectParameter("ReceptionOrderID", typeof(int));
    
            var messageStatusIDParameter = messageStatusID.HasValue ?
                new ObjectParameter("MessageStatusID", messageStatusID) :
                new ObjectParameter("MessageStatusID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prShipmentOrderSetSent", receptionOrderIDParameter, messageStatusIDParameter, returnValue, returnMessage);
        }
    
        public virtual int prCdlItemsSetSent(Nullable<int> itemID, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var itemIDParameter = itemID.HasValue ?
                new ObjectParameter("ItemID", itemID) :
                new ObjectParameter("ItemID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prCdlItemsSetSent", itemIDParameter, returnValue, returnMessage);
        }
    
        public virtual int prCdlKitsSetSent(Nullable<int> itemID, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var itemIDParameter = itemID.HasValue ?
                new ObjectParameter("ItemID", itemID) :
                new ObjectParameter("ItemID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prCdlKitsSetSent", itemIDParameter, returnValue, returnMessage);
        }
    
        public virtual int prGetIntValueFromCounter(string counterName, ObjectParameter newValue)
        {
            var counterNameParameter = counterName != null ?
                new ObjectParameter("CounterName", counterName) :
                new ObjectParameter("CounterName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prGetIntValueFromCounter", counterNameParameter, newValue);
        }
    
        public virtual int prAppLogWriteNew(string type, string message, string xmlDeclaration, string xmlMessage, Nullable<int> userId, string source, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var messageParameter = message != null ?
                new ObjectParameter("Message", message) :
                new ObjectParameter("Message", typeof(string));
    
            var xmlDeclarationParameter = xmlDeclaration != null ?
                new ObjectParameter("XmlDeclaration", xmlDeclaration) :
                new ObjectParameter("XmlDeclaration", typeof(string));
    
            var xmlMessageParameter = xmlMessage != null ?
                new ObjectParameter("XmlMessage", xmlMessage) :
                new ObjectParameter("XmlMessage", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var sourceParameter = source != null ?
                new ObjectParameter("Source", source) :
                new ObjectParameter("Source", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prAppLogWriteNew", typeParameter, messageParameter, xmlDeclarationParameter, xmlMessageParameter, userIdParameter, sourceParameter, returnValue, returnMessage);
        }
    
        public virtual int prRefurbishedOrderSetSent(Nullable<int> refurbishedOrderID, Nullable<int> messageStatusID, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var refurbishedOrderIDParameter = refurbishedOrderID.HasValue ?
                new ObjectParameter("RefurbishedOrderID", refurbishedOrderID) :
                new ObjectParameter("RefurbishedOrderID", typeof(int));
    
            var messageStatusIDParameter = messageStatusID.HasValue ?
                new ObjectParameter("MessageStatusID", messageStatusID) :
                new ObjectParameter("MessageStatusID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prRefurbishedOrderSetSent", refurbishedOrderIDParameter, messageStatusIDParameter, returnValue, returnMessage);
        }
    
        public virtual int prEmailSentGetHashCount(string emailMessageHash, ObjectParameter hashCount, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var emailMessageHashParameter = emailMessageHash != null ?
                new ObjectParameter("EmailMessageHash", emailMessageHash) :
                new ObjectParameter("EmailMessageHash", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prEmailSentGetHashCount", emailMessageHashParameter, hashCount, returnValue, returnMessage);
        }
    
        public virtual int prEmailSentWrite(string type, string emailFrom, string emailTo, string emailSubject, string emailMessageHash, string emailMessage, string embededPicture, Nullable<int> userId, string source, Nullable<bool> isInternal, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var emailFromParameter = emailFrom != null ?
                new ObjectParameter("EmailFrom", emailFrom) :
                new ObjectParameter("EmailFrom", typeof(string));
    
            var emailToParameter = emailTo != null ?
                new ObjectParameter("EmailTo", emailTo) :
                new ObjectParameter("EmailTo", typeof(string));
    
            var emailSubjectParameter = emailSubject != null ?
                new ObjectParameter("EmailSubject", emailSubject) :
                new ObjectParameter("EmailSubject", typeof(string));
    
            var emailMessageHashParameter = emailMessageHash != null ?
                new ObjectParameter("EmailMessageHash", emailMessageHash) :
                new ObjectParameter("EmailMessageHash", typeof(string));
    
            var emailMessageParameter = emailMessage != null ?
                new ObjectParameter("EmailMessage", emailMessage) :
                new ObjectParameter("EmailMessage", typeof(string));
    
            var embededPictureParameter = embededPicture != null ?
                new ObjectParameter("EmbededPicture", embededPicture) :
                new ObjectParameter("EmbededPicture", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var sourceParameter = source != null ?
                new ObjectParameter("Source", source) :
                new ObjectParameter("Source", typeof(string));
    
            var isInternalParameter = isInternal.HasValue ?
                new ObjectParameter("IsInternal", isInternal) :
                new ObjectParameter("IsInternal", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prEmailSentWrite", typeParameter, emailFromParameter, emailToParameter, emailSubjectParameter, emailMessageHashParameter, emailMessageParameter, embededPictureParameter, userIdParameter, sourceParameter, isInternalParameter, returnValue, returnMessage);
        }
    
        public virtual int prDeleteMessageOrderSetSent(Nullable<int> deleteMessageOrderID, Nullable<int> messageStatusID, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var deleteMessageOrderIDParameter = deleteMessageOrderID.HasValue ?
                new ObjectParameter("DeleteMessageOrderID", deleteMessageOrderID) :
                new ObjectParameter("DeleteMessageOrderID", typeof(int));
    
            var messageStatusIDParameter = messageStatusID.HasValue ?
                new ObjectParameter("MessageStatusID", messageStatusID) :
                new ObjectParameter("MessageStatusID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prDeleteMessageOrderSetSent", deleteMessageOrderIDParameter, messageStatusIDParameter, returnValue, returnMessage);
        }
    
        public virtual int prDeleteMessageEmailSetSent(Nullable<int> deleteMessageID, Nullable<int> messageStatusID, Nullable<int> userID, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var deleteMessageIDParameter = deleteMessageID.HasValue ?
                new ObjectParameter("DeleteMessageID", deleteMessageID) :
                new ObjectParameter("DeleteMessageID", typeof(int));
    
            var messageStatusIDParameter = messageStatusID.HasValue ?
                new ObjectParameter("MessageStatusID", messageStatusID) :
                new ObjectParameter("MessageStatusID", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prDeleteMessageEmailSetSent", deleteMessageIDParameter, messageStatusIDParameter, userIDParameter, returnValue, returnMessage);
        }
    
        public virtual int prDeleteMessageEmailSetReceived(Nullable<int> deleteID, Nullable<int> deleteMessageID, Nullable<int> messageStatusID, Nullable<int> userID, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var deleteIDParameter = deleteID.HasValue ?
                new ObjectParameter("DeleteID", deleteID) :
                new ObjectParameter("DeleteID", typeof(int));
    
            var deleteMessageIDParameter = deleteMessageID.HasValue ?
                new ObjectParameter("DeleteMessageID", deleteMessageID) :
                new ObjectParameter("DeleteMessageID", typeof(int));
    
            var messageStatusIDParameter = messageStatusID.HasValue ?
                new ObjectParameter("MessageStatusID", messageStatusID) :
                new ObjectParameter("MessageStatusID", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prDeleteMessageEmailSetReceived", deleteIDParameter, deleteMessageIDParameter, messageStatusIDParameter, userIDParameter, returnValue, returnMessage);
        }
    
        public virtual int prDeleteMessageEmailSetOrderInactive(Nullable<int> deleteOrderID, Nullable<int> deleteOrderMessageID, string messageDescription, Nullable<int> userID, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var deleteOrderIDParameter = deleteOrderID.HasValue ?
                new ObjectParameter("DeleteOrderID", deleteOrderID) :
                new ObjectParameter("DeleteOrderID", typeof(int));
    
            var deleteOrderMessageIDParameter = deleteOrderMessageID.HasValue ?
                new ObjectParameter("DeleteOrderMessageID", deleteOrderMessageID) :
                new ObjectParameter("DeleteOrderMessageID", typeof(int));
    
            var messageDescriptionParameter = messageDescription != null ?
                new ObjectParameter("MessageDescription", messageDescription) :
                new ObjectParameter("MessageDescription", typeof(string));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prDeleteMessageEmailSetOrderInactive", deleteOrderIDParameter, deleteOrderMessageIDParameter, messageDescriptionParameter, userIDParameter, returnValue, returnMessage);
        }
    
        public virtual int prDeleteMessageEmailSetOrderActive(Nullable<int> deleteOrderID, Nullable<int> deleteOrderMessageID, string messageDescription, Nullable<int> userID, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var deleteOrderIDParameter = deleteOrderID.HasValue ?
                new ObjectParameter("DeleteOrderID", deleteOrderID) :
                new ObjectParameter("DeleteOrderID", typeof(int));
    
            var deleteOrderMessageIDParameter = deleteOrderMessageID.HasValue ?
                new ObjectParameter("DeleteOrderMessageID", deleteOrderMessageID) :
                new ObjectParameter("DeleteOrderMessageID", typeof(int));
    
            var messageDescriptionParameter = messageDescription != null ?
                new ObjectParameter("MessageDescription", messageDescription) :
                new ObjectParameter("MessageDescription", typeof(string));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prDeleteMessageEmailSetOrderActive", deleteOrderIDParameter, deleteOrderMessageIDParameter, messageDescriptionParameter, userIDParameter, returnValue, returnMessage);
        }
    
        public virtual int prCrmOrderSetSentAndModifyCardStockItem(Nullable<int> crmOrderID, Nullable<int> statusOK, Nullable<int> messageStatusID, ObjectParameter returnValue, ObjectParameter returnMessage)
        {
            var crmOrderIDParameter = crmOrderID.HasValue ?
                new ObjectParameter("CrmOrderID", crmOrderID) :
                new ObjectParameter("CrmOrderID", typeof(int));
    
            var statusOKParameter = statusOK.HasValue ?
                new ObjectParameter("StatusOK", statusOK) :
                new ObjectParameter("StatusOK", typeof(int));
    
            var messageStatusIDParameter = messageStatusID.HasValue ?
                new ObjectParameter("MessageStatusID", messageStatusID) :
                new ObjectParameter("MessageStatusID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prCrmOrderSetSentAndModifyCardStockItem", crmOrderIDParameter, statusOKParameter, messageStatusIDParameter, returnValue, returnMessage);
        }
    }
}
