//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenixAutomat
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCMRF0Sent
    {
        public int ID { get; set; }
        public int MessageId { get; set; }
        public int MessageTypeId { get; set; }
        public string MessageDescription { get; set; }
        public Nullable<System.DateTime> MessageDateOfShipment { get; set; }
        public int CustomerID { get; set; }
        public int MessageStatusId { get; set; }
        public string CustomerDescription { get; set; }
        public System.DateTime DateOfDelivery { get; set; }
        public bool IsManually { get; set; }
        public int StockId { get; set; }
        public string Notice { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int ModifyUserId { get; set; }
        public Nullable<int> OrganisationNumber { get; set; }
        public string CompanyName { get; set; }
        public string CustomerCity { get; set; }
        public string StreetName { get; set; }
        public string StreetOrientationNumber { get; set; }
        public string StreetHouseNumber { get; set; }
        public string ZipCode { get; set; }
        public string IdCountry { get; set; }
        public string ICO { get; set; }
        public string DIC { get; set; }
        public string Type { get; set; }
        public bool IsSent { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public string CountryISO { get; set; }
        public bool DpIsActive { get; set; }
        public System.DateTime DpModifyDate { get; set; }
        public int DpModifyUserId { get; set; }
        public string DescriptionCz { get; set; }
        public int Reconciliation { get; set; }
        public string ModifyUserLastName { get; set; }
        public string ModifyUserFirstName { get; set; }
    }
}
