//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenixAutomat
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCMRF0SentIt
    {
        public int ID { get; set; }
        public int CMSOId { get; set; }
        public int ItemVerKit { get; set; }
        public string ItemVerKitText { get; set; }
        public int ItemOrKitID { get; set; }
        public string ItemOrKitDescription { get; set; }
        public decimal ItemOrKitQuantity { get; set; }
        public Nullable<decimal> ItemOrKitQuantityDelivered { get; set; }
        public Nullable<int> ItemOrKitQuantityInt { get; set; }
        public Nullable<int> ItemOrKitQuantityDeliveredInt { get; set; }
        public int ItemOrKitUnitOfMeasureId { get; set; }
        public string ItemOrKitUnitOfMeasure { get; set; }
        public int ItemOrKitQualityId { get; set; }
        public string ItemOrKitQualityCode { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int ModifyUserId { get; set; }
    }
}
