//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenixAutomat
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCMKSent
    {
        public int ID { get; set; }
        public int MessageId { get; set; }
        public int MessageTypeID { get; set; }
        public string MessageDescription { get; set; }
        public Nullable<System.DateTime> MessageDateOfShipment { get; set; }
        public int MessageStatusId { get; set; }
        public System.DateTime KitDateOfDelivery { get; set; }
        public int StockId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int ModifyUserId { get; set; }
        public string CompanyName { get; set; }
        public string DescriptionCz { get; set; }
        public int Code { get; set; }
        public Nullable<int> HeliosOrderID { get; set; }
        public int Reconciliation { get; set; }
        public Nullable<System.DateTime> RealCompletationDate { get; set; }
        public Nullable<decimal> KitQuantity { get; set; }
        public Nullable<decimal> KitQuantityDelivered { get; set; }
        public int KitID { get; set; }
        public string ModelCPE { get; set; }
    }
}
